---
# This file is used for the development environment.

services:
  devcontainer:
    image: golang:1.25.0
    volumes:
      - .:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: "host.docker.internal"

  mongodb:
    build:
      context: ./build/deps
      dockerfile: mongodb.Dockerfile
    command: --config /etc/mongodb.conf
    ports:
      - 27001:27001
    environment:
      # Always UTC+05:45. Set to catch timezone problems.
      TZ: Asia/Kathmandu
    volumes:
      - ./build/mongodb.conf:/etc/mongodb.conf
      - ./tmp/testscripts:/testscripts

  ferretdb:
    build:
      context: ./build/deps
      dockerfile: ferretdb.Dockerfile
    ports:
      - 27002:27017
    environment:
      # Always UTC+05:45. Set to catch timezone problems.
      TZ: Asia/Kathmandu
      FERRETDB_AUTH: false
      POSTGRES_USERNAME: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
